/*Comando para remoção de todas as tuplas da tabela*/
/*TRUNCATE TABLE Acidente;*/ 

/*Nome da tabela:Acidente*/
/*Estrutura da tabela:
    Acidente (
    idAcidente_PK INT PRIMARY KEY,
    descricao VARCHAR(600),
    data_acidente DATE,
    id_seguradora_FK INT,
    id_pedido_FK INT
    );
*/

insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (1, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2019-04-16', 2, 130);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (2, 'Nulla tempus.', '2008-11-26', 18, 85);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (3, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2003-01-25', 44, 140);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (4, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '2011-04-29', 19, 17);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (5, 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2017-06-14', 91, 52);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (6, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2002-03-04', 20, 111);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (7, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', '2012-05-09', 50, 93);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (8, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2019-06-04', 40, 76);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (9, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2012-11-19', 32, 181);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (10, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2006-06-19', 79, 63);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (11, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2013-04-06', 77, 14);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (12, 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', '2004-11-30', 94, 166);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (13, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2011-12-17', 30, 97);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (14, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2011-08-14', 60, 136);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (15, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2017-06-04', 2, 66);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (16, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2013-03-04', 68, 38);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (17, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2004-11-13', 96, 124);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (18, 'Duis ac nibh.', '2012-06-04', 66, 59);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (19, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '2010-07-29', 26, 37);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (20, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '2017-04-02', 23, 190);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (21, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2006-08-21', 46, 133);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (22, 'Vivamus tortor. Duis mattis egestas metus.', '2009-01-03', 68, 135);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (23, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2009-12-01', 56, 168);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (24, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2002-11-22', 11, 99);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (25, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2000-06-04', 36, 40);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (26, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2018-02-22', 10, 188);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (27, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2017-07-29', 64, 85);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (28, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2011-12-15', 61, 191);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (29, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2013-09-29', 21, 94);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (30, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2000-06-18', 48, 140);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (31, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2007-07-15', 15, 24);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (32, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', '2012-11-07', 26, 190);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (33, 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2017-01-02', 1, 58);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (34, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', '2009-10-02', 41, 10);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (35, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2016-12-10', 66, 28);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (36, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2015-12-12', 82, 28);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (37, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2007-06-22', 23, 2);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (38, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', '2003-05-30', 57, 3);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (39, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2015-08-22', 61, 13);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (40, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2010-03-23', 43, 191);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (41, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2013-09-03', 84, 145);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (42, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '2001-01-25', 8, 185);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (43, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2004-01-05', 69, 138);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (44, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2013-08-15', 37, 80);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (45, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2003-02-11', 89, 148);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (46, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2011-10-15', 61, 134);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (47, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '2015-08-06', 45, 113);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (48, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2018-08-21', 66, 30);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (49, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2003-11-03', 11, 122);
insert into Acidente (idacidente_pk, descricao, data_acidente, id_seguradora_fk, id_pedido_fk) values (50, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2003-08-17', 2, 49);
