/*Nome da tabela:Veiculo*/
/*Estrutura da tabela:
    Veiculo (
    idVeiculo_PK INT PRIMARY KEY,
    numMaxContainers INT,
    localizacao VARCHAR(30),
    fabricante VARCHAR(20),
    capacidadeCombustivel DOUBLE,
    cargaMaxima DOUBLE,
    statusVeiculo ENUM('Disponivel','Em uso','Em manutenção','Desmobilizado'),
    unidadeOrigem_FK INT,
    tempoUtilizacao INT,
    lotacaoAtual INT,
    disponibilidade BOOLEAN,
    tipoVeiculo ENUM('Trem', 'Navio', 'Caminhão')
    );
*/

insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (1, 6, '167 Porter Street', 'Hyundai', 36.57, 4087.21, 'Desmobilizado', 23, 129, 2, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (2, 20, '00 Manley Hill', 'Plymouth', 97.87, 8182.98, 'Disponivel', 100, 218, 19, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (3, 10, '244 Johnson Drive', 'Chevrolet', 82.54, 685.26, 'Em manutenção', 87, 98, 2, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (4, 19, '19 Pearson Pass', 'Chrysler', 27.15, 8816.57, 'Disponivel', 69, 14, 2, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (5, 7, '3 Gulseth Place', 'Mitsubishi', 26.9, 9966.27, 'Em manutenção', 33, 107, 18, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (6, 20, '344 Ohio Way', 'Mazda', 1.33, 8867.49, 'Em manutenção', 75, 168, 10, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (7, 4, '1 Morningstar Junction', 'Chevrolet', 94.91, 8040.9, 'Desmobilizado', 50, 228, 6, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (8, 14, '06213 Westend Trail', 'Chevrolet', 52.35, 8103.45, 'Em manutenção', 67, 48, 16, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (9, 4, '5149 Barnett Trail', 'Suzuki', 28.27, 9970.72, 'Disponivel', 29, 160, 10, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (10, 11, '467 Carey Terrace', 'Cadillac', 99.25, 5676.64, 'Em uso', 89, 7, 17, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (11, 8, '47 Corscot Circle', 'Mitsubishi', 11.0, 2811.04, 'Em uso', 52, 223, 10, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (12, 19, '855 Anthes Circle', 'Ford', 41.16, 8758.67, 'Em uso', 27, 184, 20, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (13, 20, '31 Tomscot Point', 'Volvo', 24.26, 7854.18, 'Em manutenção', 50, 215, 16, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (14, 11, '85 Redwing Avenue', 'McLaren', 42.05, 653.9, 'Desmobilizado', 51, 160, 20, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (15, 17, '17 Scoville Way', 'Mitsubishi', 83.26, 9054.38, 'Desmobilizado', 27, 231, 9, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (16, 7, '1 Talmadge Alley', 'Buick', 86.96, 1373.22, 'Em manutenção', 85, 111, 1, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (17, 18, '30302 Doe Crossing Place', 'Toyota', 43.57, 4017.28, 'Desmobilizado', 63, 176, 10, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (18, 17, '24716 Nelson Trail', 'Audi', 28.25, 8683.92, 'Em uso', 4, 48, 4, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (19, 14, '0284 Oak Point', 'Chevrolet', 83.88, 6196.48, 'Disponivel', 91, 207, 20, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (20, 13, '5 Oxford Junction', 'Audi', 70.83, 1017.03, 'Em uso', 14, 30, 20, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (21, 19, '488 Northridge Crossing', 'Porsche', 10.63, 6776.18, 'Desmobilizado', 93, 128, 6, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (22, 10, '94962 Drewry Street', 'Cadillac', 91.15, 935.68, 'Em uso', 41, 53, 1, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (23, 20, '8 Rigney Hill', 'Toyota', 47.24, 9117.0, 'Disponivel', 42, 9, 1, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (24, 4, '118 Butterfield Court', 'Audi', 96.15, 2566.49, 'Desmobilizado', 46, 114, 13, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (25, 15, '886 Jana Junction', 'Saab', 55.08, 5801.51, 'Em manutenção', 100, 120, 19, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (26, 3, '0530 2nd Lane', 'GMC', 53.5, 8757.96, 'Disponivel', 17, 92, 18, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (27, 1, '1 Ryan Parkway', 'Volkswagen', 3.08, 9517.39, 'Disponivel', 18, 40, 19, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (28, 13, '4293 Continental Center', 'Lexus', 85.41, 6357.34, 'Desmobilizado', 19, 208, 2, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (29, 15, '00268 Menomonie Avenue', 'Audi', 39.19, 2202.26, 'Disponivel', 14, 90, 16, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (30, 9, '4 Onsgard Pass', 'Buick', 84.08, 532.91, 'Disponivel', 72, 204, 1, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (31, 19, '649 Morningstar Point', 'Ram', 94.58, 1334.19, 'Em manutenção', 15, 231, 13, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (32, 17, '2 Petterle Parkway', 'Mazda', 10.65, 3098.8, 'Desmobilizado', 50, 87, 6, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (33, 11, '1115 Lindbergh Terrace', 'Chevrolet', 51.38, 2024.95, 'Em uso', 12, 153, 15, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (34, 11, '9 Loftsgordon Drive', 'Volvo', 63.99, 8176.9, 'Desmobilizado', 24, 122, 11, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (35, 4, '3871 Anzinger Pass', 'Saab', 9.55, 2054.98, 'Em uso', 81, 232, 10, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (36, 7, '7 Superior Terrace', 'Toyota', 96.61, 126.33, 'Disponivel', 23, 130, 11, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (37, 15, '13835 Everett Hill', 'Dodge', 22.11, 8229.75, 'Em manutenção', 100, 91, 12, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (38, 11, '4951 Mockingbird Park', 'Chevrolet', 70.49, 3180.35, 'Em manutenção', 83, 39, 6, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (39, 10, '98 Lake View Court', 'Toyota', 52.05, 1273.25, 'Disponivel', 81, 192, 5, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (40, 6, '8361 Southridge Point', 'Dodge', 45.71, 1241.03, 'Em uso', 44, 66, 10, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (41, 1, '57022 Jay Court', 'Buick', 11.49, 575.13, 'Em manutenção', 97, 231, 11, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (42, 4, '8501 Amoth Center', 'Mercedes-Benz', 81.21, 4286.16, 'Em manutenção', 66, 25, 18, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (43, 8, '96 Warner Hill', 'Lotus', 54.56, 848.01, 'Em uso', 15, 99, 19, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (44, 5, '28883 Sunfield Parkway', 'Hyundai', 6.76, 1005.68, 'Disponivel', 59, 115, 16, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (45, 20, '12859 Charing Cross Hill', 'Hyundai', 87.44, 7969.7, 'Desmobilizado', 57, 96, 7, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (46, 9, '497 8th Street', 'Plymouth', 70.3, 4024.03, 'Em uso', 5, 48, 3, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (47, 15, '9 Randy Lane', 'Oldsmobile', 96.2, 6918.97, 'Em manutenção', 10, 5, 14, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (48, 7, '34 Goodland Park', 'Mitsubishi', 23.21, 5467.98, 'Em manutenção', 86, 66, 9, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (49, 2, '6589 Schlimgen Trail', 'Porsche', 35.13, 6203.45, 'Em manutenção', 77, 62, 3, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (50, 9, '67758 Badeau Junction', 'GMC', 34.21, 8775.28, 'Disponivel', 25, 127, 4, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (51, 8, '059 Starling Court', 'Toyota', 14.49, 3920.26, 'Em uso', 76, 70, 2, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (52, 12, '70 Southridge Road', 'Pontiac', 77.21, 9449.53, 'Disponivel', 29, 132, 7, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (53, 13, '48858 Fallview Hill', 'Dodge', 11.54, 4233.63, 'Disponivel', 11, 195, 20, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (54, 12, '8 Coleman Alley', 'Toyota', 20.9, 2095.78, 'Desmobilizado', 63, 83, 13, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (55, 10, '74048 Coolidge Plaza', 'GMC', 89.77, 9657.97, 'Disponivel', 81, 33, 8, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (56, 12, '359 Iowa Court', 'Mitsubishi', 89.2, 3725.47, 'Disponivel', 100, 169, 2, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (57, 8, '5630 Kedzie Street', 'Mercury', 51.09, 4216.04, 'Em manutenção', 84, 157, 16, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (58, 5, '81 Everett Place', 'Chevrolet', 59.69, 8671.92, 'Em manutenção', 59, 125, 13, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (59, 17, '94916 Birchwood Lane', 'Mercedes-Benz', 5.13, 6117.04, 'Em uso', 32, 156, 11, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (60, 15, '57390 Kipling Plaza', 'Chevrolet', 32.0, 4081.64, 'Desmobilizado', 6, 169, 1, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (61, 19, '56 Canary Point', 'Oldsmobile', 68.59, 8046.66, 'Em uso', 2, 12, 18, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (62, 12, '29 Muir Court', 'Suzuki', 9.22, 7382.15, 'Disponivel', 7, 196, 3, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (63, 13, '5 Merrick Way', 'GMC', 33.34, 6172.52, 'Desmobilizado', 36, 83, 10, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (64, 19, '29 Little Fleur Lane', 'Pontiac', 57.19, 5971.2, 'Em manutenção', 79, 125, 1, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (65, 3, '77 Anzinger Street', 'Dodge', 9.49, 1380.25, 'Desmobilizado', 78, 177, 7, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (66, 19, '6 Pepper Wood Junction', 'Cadillac', 3.29, 4892.88, 'Disponivel', 24, 218, 5, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (67, 3, '2756 Cherokee Alley', 'Dodge', 9.92, 5274.14, 'Disponivel', 76, 80, 15, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (68, 11, '90510 Katie Drive', 'Mitsubishi', 63.97, 1218.17, 'Disponivel', 23, 125, 16, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (69, 4, '0371 Nova Court', 'Chevrolet', 94.78, 663.85, 'Em manutenção', 4, 142, 1, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (70, 4, '8113 Anzinger Junction', 'Honda', 54.81, 4442.66, 'Em uso', 18, 230, 1, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (71, 2, '63 Waxwing Way', 'Chevrolet', 4.94, 3111.6, 'Disponivel', 16, 2, 1, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (72, 8, '441 Del Sol Lane', 'Ford', 99.93, 1685.42, 'Em manutenção', 9, 103, 14, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (73, 19, '21 Brickson Park Parkway', 'Volkswagen', 3.35, 727.35, 'Em manutenção', 47, 89, 12, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (74, 17, '2951 Spaight Parkway', 'Chevrolet', 42.51, 5583.16, 'Em uso', 2, 113, 18, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (75, 7, '829 Westend Street', 'Ford', 48.7, 4249.39, 'Em uso', 80, 240, 7, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (76, 3, '7089 1st Alley', 'Dodge', 69.32, 1933.51, 'Em manutenção', 28, 159, 9, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (77, 9, '57 Anderson Crossing', 'Toyota', 91.89, 7385.85, 'Desmobilizado', 8, 169, 6, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (78, 16, '33128 Mendota Circle', 'Lamborghini', 71.91, 4410.34, 'Disponivel', 64, 233, 5, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (79, 9, '41 Granby Court', 'Porsche', 53.12, 5672.89, 'Em uso', 36, 145, 11, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (80, 20, '56 Moose Plaza', 'Volkswagen', 98.87, 824.2, 'Em uso', 26, 92, 15, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (81, 7, '66698 Mccormick Junction', 'Chevrolet', 58.28, 8030.8, 'Em uso', 96, 80, 5, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (82, 10, '2127 Valley Edge Trail', 'Dodge', 2.12, 6521.58, 'Desmobilizado', 68, 77, 11, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (83, 3, '03950 Melby Circle', 'Toyota', 88.67, 6605.91, 'Desmobilizado', 47, 191, 2, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (84, 6, '39512 Heath Lane', 'BMW', 74.37, 6004.07, 'Desmobilizado', 16, 122, 9, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (85, 10, '47171 Upham Pass', 'Mazda', 88.27, 6712.5, 'Em uso', 26, 106, 9, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (86, 9, '84350 Summit Circle', 'GMC', 12.05, 2295.76, 'Em uso', 84, 75, 20, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (87, 12, '00 Kings Pass', 'Acura', 77.18, 3245.74, 'Em manutenção', 90, 3, 10, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (88, 11, '1 Mccormick Drive', 'Chevrolet', 25.34, 9085.19, 'Em manutenção', 75, 134, 3, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (89, 11, '790 Anhalt Center', 'Mercedes-Benz', 83.79, 1877.96, 'Desmobilizado', 17, 119, 5, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (90, 10, '0603 Fair Oaks Parkway', 'Saturn', 39.28, 9606.68, 'Em uso', 77, 174, 16, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (91, 10, '9 Holmberg Junction', 'Ford', 71.09, 6778.37, 'Desmobilizado', 21, 31, 5, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (92, 16, '5373 Pine View Park', 'Daewoo', 21.77, 2516.04, 'Disponivel', 50, 192, 18, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (93, 8, '97 Boyd Circle', 'Peugeot', 20.14, 8151.42, 'Disponivel', 39, 197, 1, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (94, 17, '8689 Prentice Avenue', 'Cadillac', 70.78, 2648.99, 'Em manutenção', 44, 203, 18, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (95, 8, '03 Browning Park', 'Pontiac', 45.81, 2864.58, 'Disponivel', 4, 168, 15, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (96, 16, '04239 Commercial Center', 'Ford', 58.77, 8605.05, 'Desmobilizado', 16, 180, 5, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (97, 14, '4 Ludington Street', 'Acura', 12.34, 6022.92, 'Desmobilizado', 88, 77, 5, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (98, 10, '06753 Amoth Park', 'Land Rover', 3.96, 6071.76, 'Em manutenção', 96, 191, 11, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (99, 12, '167 Manitowish Street', 'Ford', 51.29, 3732.88, 'Em uso', 17, 227, 15, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (100, 7, '6887 Almo Park', 'Land Rover', 60.43, 7838.89, 'Desmobilizado', 91, 174, 18, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (101, 1, '8107 Jenna Street', 'GMC', 68.78, 6470.71, 'Desmobilizado', 72, 134, 13, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (102, 14, '4 Graedel Avenue', 'Maserati', 88.33, 3179.21, 'Disponivel', 39, 238, 9, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (103, 13, '821 Schmedeman Hill', 'Mercedes-Benz', 83.08, 3353.83, 'Em uso', 29, 199, 8, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (104, 11, '67 Killdeer Trail', 'BMW', 62.98, 4743.8, 'Em manutenção', 48, 65, 4, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (105, 20, '74325 Luster Junction', 'Ford', 13.93, 8817.29, 'Em uso', 36, 220, 12, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (106, 10, '38933 Lake View Court', 'GMC', 48.01, 3230.38, 'Disponivel', 70, 42, 7, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (107, 15, '3 Northport Point', 'Oldsmobile', 67.78, 1446.4, 'Desmobilizado', 73, 137, 7, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (108, 11, '5777 Goodland Street', 'Lincoln', 22.81, 4342.11, 'Desmobilizado', 86, 160, 18, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (109, 5, '20473 Gerald Plaza', 'Oldsmobile', 54.6, 6061.79, 'Em uso', 17, 151, 3, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (110, 9, '45507 Park Meadow Circle', 'Kia', 49.65, 6368.17, 'Disponivel', 69, 34, 3, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (111, 7, '69242 Heath Avenue', 'Mercury', 17.71, 4340.36, 'Desmobilizado', 46, 199, 13, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (112, 8, '9251 Iowa Terrace', 'Subaru', 79.18, 1840.65, 'Em manutenção', 44, 187, 2, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (113, 15, '8855 Waxwing Street', 'Ferrari', 74.38, 3871.04, 'Em manutenção', 18, 226, 6, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (114, 10, '7 Cascade Point', 'Saturn', 76.53, 6166.25, 'Em uso', 88, 221, 4, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (115, 6, '579 Spohn Crossing', 'Jeep', 75.93, 5540.96, 'Em manutenção', 26, 148, 6, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (116, 13, '214 Di Loreto Drive', 'Honda', 58.27, 8692.13, 'Disponivel', 19, 113, 11, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (117, 19, '687 Pawling Drive', 'Volvo', 31.74, 9776.28, 'Disponivel', 80, 133, 8, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (118, 8, '7521 Derek Point', 'Ford', 38.78, 8126.26, 'Desmobilizado', 28, 185, 20, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (119, 7, '34 Ludington Drive', 'Mitsubishi', 32.26, 4254.67, 'Em uso', 47, 224, 18, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (120, 1, '6202 Doe Crossing Avenue', 'Buick', 53.3, 572.42, 'Desmobilizado', 83, 60, 11, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (121, 17, '26 Fair Oaks Hill', 'Lexus', 80.81, 2005.44, 'Em uso', 37, 49, 14, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (122, 7, '94901 Elka Lane', 'GMC', 14.82, 2183.7, 'Em manutenção', 91, 62, 9, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (123, 1, '22 Blaine Road', 'Kia', 95.4, 4929.0, 'Desmobilizado', 88, 60, 19, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (124, 16, '57687 Summer Ridge Junction', 'GMC', 61.86, 2660.79, 'Em manutenção', 45, 53, 6, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (125, 12, '75710 Burning Wood Court', 'Lexus', 35.18, 3958.26, 'Desmobilizado', 84, 112, 1, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (126, 6, '49 Pepper Wood Trail', 'Nissan', 35.3, 7607.69, 'Disponivel', 96, 37, 10, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (127, 5, '0 Basil Avenue', 'Ford', 20.94, 7613.8, 'Em uso', 72, 101, 13, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (128, 3, '16135 Basil Trail', 'Acura', 60.93, 4214.56, 'Desmobilizado', 44, 195, 5, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (129, 16, '7669 Trailsway Crossing', 'Mercury', 68.14, 2720.89, 'Disponivel', 53, 27, 16, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (130, 4, '38 Shoshone Alley', 'Audi', 32.32, 9221.84, 'Em manutenção', 20, 57, 2, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (131, 7, '2 Stuart Drive', 'Honda', 15.33, 6354.37, 'Em uso', 71, 81, 13, false, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (132, 11, '66447 Hallows Center', 'Subaru', 6.58, 1614.48, 'Em uso', 19, 106, 18, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (133, 15, '2 Ramsey Pass', 'GMC', 98.25, 7159.55, 'Em uso', 61, 68, 8, true, 'Caminhão');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (134, 18, '23623 Golden Leaf Way', 'Chevrolet', 17.29, 5807.73, 'Em manutenção', 70, 124, 12, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (135, 16, '42072 Loeprich Place', 'Audi', 28.53, 2599.5, 'Disponivel', 79, 101, 16, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (136, 8, '9176 Westridge Center', 'Chevrolet', 79.68, 6700.23, 'Em manutenção', 31, 142, 20, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (137, 12, '2712 Lukken Street', 'GMC', 87.59, 3077.25, 'Em uso', 31, 54, 16, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (138, 2, '7 Loftsgordon Lane', 'Mercedes-Benz', 51.89, 697.23, 'Desmobilizado', 93, 71, 15, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (139, 14, '85649 Raven Way', 'Buick', 72.64, 3878.94, 'Em uso', 74, 138, 18, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (140, 19, '349 Stuart Crossing', 'Audi', 9.23, 7202.69, 'Em manutenção', 10, 199, 11, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (141, 16, '46306 Thompson Place', 'Volkswagen', 26.5, 618.94, 'Disponivel', 4, 34, 14, true, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (142, 16, '668 Redwing Way', 'Mazda', 73.07, 490.28, 'Em uso', 27, 12, 1, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (143, 6, '00372 Erie Court', 'Ford', 25.34, 3797.0, 'Em uso', 65, 78, 18, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (144, 8, '1844 Coleman Alley', 'Pontiac', 50.45, 7084.29, 'Desmobilizado', 72, 115, 10, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (145, 17, '37541 Colorado Park', 'Audi', 9.26, 7667.21, 'Disponivel', 29, 224, 3, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (146, 19, '4 Scoville Avenue', 'Eagle', 76.25, 3740.37, 'Em uso', 42, 206, 1, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (147, 13, '582 Fulton Crossing', 'Saab', 43.78, 7430.28, 'Disponivel', 44, 137, 20, false, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (148, 12, '48059 Summit Point', 'Chevrolet', 24.08, 1242.15, 'Em uso', 27, 92, 13, false, 'Trem');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (149, 17, '0 Onsgard Road', 'Audi', 64.57, 4991.67, 'Em uso', 96, 153, 18, true, 'Navio');
insert into Veiculo (idveiculo_pk, nummaxcontainers, localizacao, fabricante, capacidadecombustivel, cargamaxima, statusveiculo, unidadeorigem_fk, tempoutilizacao, lotacaoatual, disponibilidade, tipoveiculo) values (150, 18, '25077 Southridge Place', 'Mercedes-Benz', 81.05, 2148.36, 'Desmobilizado', 42, 23, 6, false, 'Caminhão');
